services:
  nginx:
    build:
      context: ./requirements/nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb_data:

networks:
  inception:
    driver: bridge