services:
  nginx:
    build: 
      context: requirements/nginx/.
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - v_web:/var/www/html
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - v_web:/var/www/html
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - v_db:/var/lib/mysql
volumes:
  v_web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jorteixe/data/wordpress
  v_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jorteixe/data/mariadb
networks:
  inception:
    driver: bridge