services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/.
    networks:
      - inception
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./home/jorteixe/data/mariadb


networks:
  inception:
    driver: bridge
